### ISSUE TITLE
Is there a list of the images that are provided with this presence?

### ISSUE THREAD

**Issue by LawMixer** [iArxic/StudioPresence#22]
I'm rewriting this plugin in Python, with the same features and some different features and I was wondering if you could provide the images that the presence uses. I'll make sure to credit you and everything, after all it is a fork. 

Thanks!

**Comment by iArxic** [comment]
Hey there, you can use this application id:
**1028311936854675458**

This is for 'Playing **Roblox Studio**'
![image](https://github.com/iArxic/StudioPresence/assets/77511250/a8139061-155d-4fff-8e0c-ee66fdc78fc2)
Those are the names for each image

Here are the RAW images if you wish to create your own discord application for this:
![modulescriptbetter](https://github.com/iArxic/StudioPresence/assets/77511250/81ec0898-2b53-4e43-ab5a-5fbed0eb5e3b)
![clientbetter](https://github.com/iArxic/StudioPresence/assets/77511250/6cfc3c3e-7380-4dc6-8e50-bb6e3864f06b)
![buildingbetter2](https://github.com/iArxic/StudioPresence/assets/77511250/7ba01ef9-2e25-4612-bf10-98d82cc0fae3)
![studiobetter](https://github.com/iArxic/StudioPresence/assets/77511250/1ba6f560-ae62-4a7b-b17d-a9f8df30d129)
![serverscriptbetter](https://github.com/iArxic/StudioPresence/assets/77511250/dbb88db7-2bb3-4771-a7c9-49c517a34c22)
