### ISSUE TITLE
RPC doesn't clear once Roblox Studio closes

### ISSUE THREAD

**Issue by TymonMarek** [iArxic/StudioPresence#3]
![image](https://user-images.githubusercontent.com/117597583/206921659-fb062cf4-4968-4ef9-bf68-f4ed89c84dd8.png)

<s>Unsure if this is an issue with [Coyenn's](https://github.com/Coyenn) fork or the main branch.</s> Merged fork

**Comment by iArxic** [comment]
thanks for the report i'm looking into it

**Comment by iArxic** [comment]
fixed
